name: Deploy Jumper Doc Container
on:
  create:
    tags:
      - '*'

jobs:
  Deploy-Jumper-Doc-Container:
    runs-on: ubuntu-latest
    env:
      REMOTE_VOLUME_DIR: /volume2/docker/jumper-doc/
      DOCKER_COMPOSE_PATH: /usr/local/bin/docker-compose
    steps:
      - uses: actions/checkout@v3

      - name: Build Jumper Doc
        run: |
          npm install
          npm run docs:build
          # Crée le répertoire public dans 'deploy/' qui sera transféré
          cp -r .vitepress/dist deploy/public

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Remote Host Key to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Prepare Remote Directory (mkdir & chmod)
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.SSH_HOST }} 'bash -s' <<EOF
          # Crée le répertoire s'il n'existe pas et s'assure qu'il est accessible
          mkdir -p ${{ env.REMOTE_VOLUME_DIR }}
          chmod 755 ${{ env.REMOTE_VOLUME_DIR }}
          EOF

      - name: Copy files via rsync (SSH)
        run: |
          # rsync utilise l'agent SSH et la clé ajoutée
          rsync -avzr --delete deploy/ ${{ secrets.REMOTE_USER }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_VOLUME_DIR }}

      - name: Run docker compose file
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.SSH_HOST }} 'bash -s' <<EOF
          cd ${{ env.REMOTE_VOLUME_DIR }}
          # Utilise le chemin spécifié pour docker-compose
          ${{ env.DOCKER_COMPOSE_PATH }} up -d --force-recreate
          EOF
